export const RIGHT_IS_IN_BRASIL = 'RIGHT_IS_IN_BRASIL'

export const LEFT_IS_CAPITAL = 'LEFT_IS_CAPITAL'

export const RIGHT_IS_CAPITAL = 'RIGHT_IS_CAPITAL'

export const LEFT_IS_IN_BRASIL = 'LEFT_IS_IN_BRASIL'

export const LEFT_IS_IN_AMERICAS = 'LEFT_IS_IN_AMERICAS'

export const RIGHT_IS_IN_AMERICAS = 'RIGHT_IS_IN_AMERICAS'

export const LEFT_IS_CLOSE_TO_COAST = 'LEFT_IS_CLOSE_TO_COAST'

export const RIGHT_IS_CLOSE_TO_COAST = 'RIGHT_IS_CLOSE_TO_COAST'

export const LEFT_IS_FAMOUS_FOR_ITS_WATERS = 'LEFT_IS_FAMOUS_FOR_ITS_WATERS'

export const RIGHT_IS_FAMOUS_FOR_ITS_WATERS = 'RIGHT_IS_FAMOUS_FOR_ITS_WATERS'

export const LEFT_IS_FAMOUS_FOR_CULINARY = 'LEFT_IS_FAMOUS_FOR_CULINARY'

export const RIGHT_IS_FAMOUS_FOR_CULINARY = 'RIGHT_IS_FAMOUS_FOR_CULINARY'

export const LEFT_EXOTIC_ANIMALS = 'LEFT_EXOTIC_ANIMALS'

export const RIGHT_EXOTIC_ANIMALS = 'RIGHT_EXOTIC_ANIMALS'

export const RIGHT_IS_IN_NORTHEAST = 'RIGHT_IS_IN_NORTHEAST'

export const LEFT_IS_IN_NORTHEAST = 'LEFT_IS_IN_NORTHEAST'

export const START = 'START'