export const RIGHT_IS_IN_BRASIL = 'RIGHT_IS_IN_BRASIL'

export const LEFT_IS_CAPITAL = 'LEFT_IS_CAPITAL'

export const RIGHT_IS_CAPITAL = 'RIGHT_IS_CAPITAL'

export const LEFT_IS_IN_BRASIL = 'LEFT_IS_IN_BRASIL'

export const LEFT_IS_IN_AMERICAS = 'LEFT_IS_IN_AMERICAS'

export const RIGHT_IS_IN_AMERICAS = 'RIGHT_IS_IN_AMERICAS'

export const LEFT_IS_CLOSE_TO_COAST = 'LEFT_IS_CLOSE_TO_COAST'

export const RIGHT_IS_CLOSE_TO_COAST = 'RIGHT_IS_CLOSE_TO_COAST'

export const LEFT_IS_FAMOUS_FOR_ITS_WATERS = 'LEFT_IS_FAMOUS_FOR_ITS_WATERS'

export const RIGHT_IS_FAMOUS_FOR_ITS_WATERS = 'RIGHT_IS_FAMOUS_FOR_ITS_WATERS'

export const LEFT_IS_FAMOUS_FOR_CULINARY = 'LEFT_IS_FAMOUS_FOR_CULINARY'

export const RIGHT_IS_FAMOUS_FOR_CULINARY = 'RIGHT_IS_FAMOUS_FOR_CULINARY'

export const LEFT_EXOTIC_ANIMALS = 'LEFT_EXOTIC_ANIMALS'

export const RIGHT_EXOTIC_ANIMALS = 'RIGHT_EXOTIC_ANIMALS'

export const RIGHT_IS_IN_NORTHEAST = 'RIGHT_IS_IN_NORTHEAST'

export const LEFT_IS_IN_NORTHEAST = 'LEFT_IS_IN_NORTHEAST'

export const LEFT_IS_KNOWN_FOR_HUMID_FLORA = 'LEFT_IS_KNOWN_FOR_HUMID_FLORA'

export const RIGHT_IS_KNOWN_FOR_HUMID_FLORA = 'RIGHT_IS_KNOWN_FOR_HUMID_FLORA'

export const LEFT_HAS_HOT_WATERS = 'LEFT_HAS_HOT_WATERS'

export const RIGHT_HAS_HOT_WATERS = 'RIGHT_HAS_HOT_WATERS'

export const LEFT_ITALIAN_AND_GERMANY_CULINARY =
	'LEFT_ITALIAN_AND_GERMANY_CULINARY'

export const RIGHT_ITALIAN_AND_GERMANY_CULINARY =
	'RIGHT_ITALIAN_AND_GERMANY_CULINARY'


export const   LEFT_IS_ABROAD_CAPITAL = 'LEFT_IS_ABROAD_CAPITAL'

export const RIGHT_IS_ABROAD_CAPITAL = 'RIGHT_IS_ABROAD_CAPITAL'

export const LEFT_BEST_SALARIES_IN_WORLD = 'LEFT_BEST_SALARIES_IN_WORLD'

export const RIGHT_BEST_SALARIES_IN_WORLD = 'RIGHT_BEST_SALARIES_IN_WORLD'

export const LEFT_IS_AN_ISLAND = 'LEFT_IS_AN_ISLAND'

export const RIGHT_IS_AN_ISLAND = 'RIGHT_IS_AN_ISLAND'

export const LEFT_HAS_A_BIG_STRAIGHT_TOWER = 'LEFT_HAS_A_BIG_STRAIGHT_TOWER'

export const RIGHT_HAS_A_BIG_STRAIGHT_TOWER = 'RIGHT_HAS_A_BIG_STRAIGHT_TOWER'

export const START = 'START'
